version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --user root --pass root --bind 0.0.0.0:8000 memory
    ports:
      - "8000:8000"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SURREALDB_URL=http://surrealdb:8000
      - ROCKSDB_PATH=/tmp/data/rocksdb
      - LEVELDB_PATH=/tmp/data/leveldb
      - API_URL=https://midgard.ninerealms.com/v2/history/runepool
      - INTERVAL=hour
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - app_data:/tmp/data
    depends_on:
      - surrealdb

volumes:
  app_data: